dist: bionic
language: python

python:
  - '3.6'

install: sudo ./.ci/install_dependencies.sh $HOME/tools

before_script:
    - export PATH=$HOME/tools:$PATH
    # the install script makes $HOME/.nextflow, owned by root with permissions
    # tha tmake the tests fail because when nextflow runs, it tries to write
    # there
    - sudo chmod 777 --recursive $HOME/.nextflow

script:
  - tox

notifications:
  email: false
